### PR TITLE
RViz locking fixed, Qt UI input for cartesian planning.

### PR DESCRIPTION
**Pull request by rkojcev**
RViz locking fixed by putting computationally heavy function for Cartesian planning to Qt Concurrent.
The parameters for generating Cartesian plan from way-points now can be set by the user.
Progress bar when loading way-points yaml files.

Please test the plugin and let me know your feedback.

### CODE REVIEW

**Comment by shaun-edwards** [comment]
Looks very good.  I've spent around half an hour playing with different cartesian paths.  I'm very happy with where we are.  I'm also pretty amazed at how well the cartesian path planner is at reaching the desired poses.  Just a couple of points/issues to add
- To @jrgnicho point, we should probably create a tutorials package with some preconfigured setups.
- It would be nice to display the % of points achieved by the cartesian planner (this is output in the logs) - please add an issue for future development
- Loading a path plan after one has already been loaded (from file) causes the plugin to lock up - please verify this and address

This PR itself does not include any changes to address the Rviz threading issue (this must have been done elsewhere).  I cannot verify these changes as a result.  This might also be the cause of the lockup mentioned above.  Please provide a pointer to the relevant changes (a link to the commit(s)).

**Comment by rkojcev** [comment]
Thanks @shaun-edwards and @jrgnicho for testing the plugin and your feedback.
- To @jrgnicho I agree with your point regarding the saved configuration of the RViz, I would be glad to contribute to the tutorials package. One note though, in the current version a robot model needs to be loaded, because the User Interactive Marker (the red arrow) needs the information of the pose of the robot end effector in order to set the initial pose of the User Interactive Marker to that one. In case if the user doesn't load a robot model and just loads the plugin with only the RViz there will be exception which is currently not handled. Also a lot of other MoveIt functions depend on loading the RobotModel, therefore I would suggest creating preconfigured setups for robot packages, for example the motoman_sia20d moveit package.
- Regarding the % of points achieved by the cartesian planner I can make the change right away.
- I will address the point why the plugin is locking.

The relevant commit regarding the change for resolving the [locking issue](https://github.com/ros-industrial-consortium/fermi/commit/0ff23d935e008c8a29d356ca0c8e3bc1dced0424).

**Comment by rkojcev** [comment]
@shaun-edwards I have tried to reproduce the issue of loading path plan after one has already been loaded and I could get lock of the Plugin only if I did not open any way-point file from the File Dialog. Is the same case when you also get a lock of the Plugin? I have managed to fix this issue, by handling the enable and disable of the TabWidget in the proper places.

**Comment by shaun-edwards** [comment]
@rkojcev, please commit this change so I can test it as part of this PR.

**Comment by shaun-edwards** [comment]
That last fix worked... +1

**Comment by rkojcev** [comment]
Great, should I merge the PR?

**Comment by shaun-edwards** [comment]
Merge away!

**Pull request merged**
